language: node_js

node_js:
  - '6'

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - export CHROME_BIN=chromium-browser
  - npm install -g yarn

install:
  - yarn install

script:
  - npm test
  - npm run build
